# NumPy Numerical Computing Foundation

---

## What is NumPy?

NumPy (**Num**erical **Py**thon) is the foundation of scientific computing in Python. It provides:
- **ndarray**: N-dimensional array object stored in contiguous memory
- **ufuncs**: Universal functions operating element-wise on arrays
- **Linear algebra**, Fourier transforms, random number generation

### Why NumPy is fast:
1. **Contiguous memory**: All elements stored in a single C-style memory block
2. **Fixed dtype**: No Python object overhead per element
3. **SIMD instructions**: CPU operates on multiple elements simultaneously
4. **Vectorization**: Loops run in C, not Python

```python
# Python list: each element is a Python object (overhead ~28 bytes each)
lst = [1.0, 2.0, 3.0]   # 3 × 28 bytes + list overhead

# NumPy array: raw C floats (8 bytes each)
arr = np.array([1.0, 2.0, 3.0])  # 3 × 8 bytes
```

## Table of Contents
1. [Array Creation](#1)
2. [Data Types (dtypes)](#2)
3. [Array Shape & Reshaping](#3)
4. [Indexing & Slicing](#4)
5. [Broadcasting](#5)
6. [Mathematical Operations & ufuncs](#6)
7. [Linear Algebra](#7)
8. [Statistics](#8)
9. [Array Manipulation](#9)
10. [Random Module](#10)
11. [Performance & Vectorization](#11)
12. [Advanced: einsum & Structured Arrays](#12)
13. [Additional Learning Resources](#13)

In [1]:
import numpy as np
print(f'NumPy version: {np.__version__}')

NumPy version: 2.4.6


---
## 1. Array Creation <a id='1'></a>

In [2]:
# From Python objects
a1 = np.array([1, 2, 3, 4, 5])                    # 1D
a2 = np.array([[1,2,3],[4,5,6]])                   # 2D
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])       # 3D
print(a1, a1.ndim, a1.shape)
print(a2, a2.shape)

# Filled arrays
print(np.zeros((3, 4)))                # all zeros
print(np.ones((2, 3)))                 # all ones
print(np.full((2, 2), 7))             # filled with constant
print(np.eye(3))                       # identity matrix
print(np.empty((2, 2)))               # uninitialized (fast)
print(np.zeros_like(a2))              # same shape as a2

# Ranges
print(np.arange(0, 10, 2))            # [0, 2, 4, 6, 8]
print(np.linspace(0, 1, 5))           # [0, 0.25, 0.5, 0.75, 1]
print(np.logspace(0, 3, 4))           # [1, 10, 100, 1000]
print(np.geomspace(1, 1000, 4))       # geometric spacing

# Special
print(np.diag([1, 2, 3]))             # diagonal matrix
print(np.tri(3, 3, k=0))              # triangular matrix
print(np.meshgrid([1,2,3],[4,5]))     # 2D grid (useful for plotting)

[1 2 3 4 5] 1 (5,)
[[1 2 3]
 [4 5 6]] (2, 3)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]
[[0 0 0]
 [0 0 0]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[   1.   10.  100. 1000.]
[   1.   10.  100. 1000.]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
(array([[1, 2, 3],
       [1, 2, 3]]), array([[4, 4, 4],
       [5, 5, 5]]))


---
## 2. Data Types (dtypes) <a id='2'></a>

Choosing the right dtype saves memory and speeds up computation.

| dtype | Size | Range / Precision |
|-------|------|------------------|
| `int8` | 1 byte | -128 to 127 |
| `int16` | 2 bytes | -32768 to 32767 |
| `int32` | 4 bytes | ±2.1 billion |
| `int64` | 8 bytes | ±9.2 quintillion |
| `float16` | 2 bytes | ~3 decimal digits |
| `float32` | 4 bytes | ~7 decimal digits |
| `float64` | 8 bytes | ~15 decimal digits |
| `complex64` | 8 bytes | 2×float32 |
| `bool` | 1 byte | True/False |

> In deep learning: `float16` (half precision) is used for GPU memory efficiency, `float32` is the default.

In [3]:
# dtype specification
a_int8   = np.array([1, 2, 3], dtype=np.int8)
a_float32 = np.array([1.0, 2.0], dtype=np.float32)
a_bool   = np.array([True, False, True], dtype=bool)
a_complex = np.array([1+2j, 3+4j], dtype=np.complex64)

print(f'int8:    {a_int8.dtype}, {a_int8.nbytes} bytes')
print(f'float32: {a_float32.dtype}, {a_float32.nbytes} bytes')

# Memory comparison
n = 1_000_000
a64 = np.ones(n, dtype=np.float64)
a32 = np.ones(n, dtype=np.float32)
a16 = np.ones(n, dtype=np.float16)
print(f'\nfloat64: {a64.nbytes/1e6:.1f} MB')
print(f'float32: {a32.nbytes/1e6:.1f} MB')
print(f'float16: {a16.nbytes/1e6:.1f} MB')

# Type conversion
a = np.array([1.7, 2.9, 3.1])
print(a.astype(int))    # floor towards zero
print(a.astype(np.float16))

# dtype info
print(np.iinfo(np.int8))   # integer type info
print(np.finfo(np.float32)) # float type info

int8:    int8, 3 bytes
float32: float32, 8 bytes

float64: 8.0 MB
float32: 4.0 MB
float16: 2.0 MB
[1 2 3]
[1.7 2.9 3.1]
Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision = 6   resolution = 1e-06
machep = -23   eps =        1.1920929e-07
negep =  -24   epsneg =     5.9604645e-08
minexp = -126   tiny =       1.1754944e-38
maxexp = 128   max =        3.4028235e+38
nexp =   8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1e-45
---------------------------------------------------------------



---
## 3. Array Shape & Reshaping <a id='3'></a>

Understanding shapes is critical for matrix operations, batch processing, and debugging DL models.

Shape conventions in deep learning:
- `(batch_size, channels, height, width)` PyTorch (NCHW)
- `(batch_size, height, width, channels)` TensorFlow (NHWC)
- `(batch_size, seq_len, embedding_dim)` Transformers

In [4]:
a = np.arange(24)
print('Original:', a.shape)          # (24,)

# reshape returns a VIEW if possible
b = a.reshape(4, 6)
print('reshape(4,6):', b.shape)      # (4, 6)
c = a.reshape(2, 3, 4)
print('reshape(2,3,4):', c.shape)    # (2, 3, 4)
d = a.reshape(4, -1)  # -1 infers dimension
print('reshape(4,-1):', d.shape)     # (4, 6)

# flatten (always returns a copy) vs ravel (returns view when possible)
print('flatten:', b.flatten().shape)  # (24,)
print('ravel:  ', b.ravel().shape)   # (24,)

# Adding/removing dimensions
x = np.array([1, 2, 3])             # shape (3,)
print('\nOriginal:', x.shape)
print('expand_dims(0):', np.expand_dims(x, 0).shape)  # (1, 3) batch dim
print('expand_dims(1):', np.expand_dims(x, 1).shape)  # (3, 1) column vec
print('x[np.newaxis]:', x[np.newaxis].shape)           # (1, 3)
print('x[:, np.newaxis]:', x[:, np.newaxis].shape)     # (3, 1)

y = np.array([[[1, 2, 3]]])         # shape (1, 1, 3)
print('squeeze:', np.squeeze(y).shape)   # (3,) removes size-1 dims
print('squeeze(0):', np.squeeze(y, 0).shape)  # (1, 3)

# Transpose
m = np.arange(12).reshape(3, 4)
print('\nOriginal shape:', m.shape)    # (3, 4)
print('Transposed:    ', m.T.shape)   # (4, 3)
print('transpose(1,0):', np.transpose(m, (1, 0)).shape)  # (4, 3)

# For 3D tensors (DL use case)
batch = np.random.randn(32, 64, 128)  # (batch, seq_len, hidden)
print('Batch shape:', batch.shape)
print('Transposed:', np.transpose(batch, (0, 2, 1)).shape)  # (batch, hidden, seq_len)

Original: (24,)
reshape(4,6): (4, 6)
reshape(2,3,4): (2, 3, 4)
reshape(4,-1): (4, 6)
flatten: (24,)
ravel:   (24,)

Original: (3,)
expand_dims(0): (1, 3)
expand_dims(1): (3, 1)
x[np.newaxis]: (1, 3)
x[:, np.newaxis]: (3, 1)
squeeze: (3,)
squeeze(0): (1, 3)

Original shape: (3, 4)
Transposed:     (4, 3)
transpose(1,0): (4, 3)
Batch shape: (32, 64, 128)
Transposed: (32, 128, 64)


---
## 4. Indexing & Slicing <a id='4'></a>

In [5]:
a = np.arange(1, 26).reshape(5, 5)
print('Array:\n', a)

# Basic indexing
print('\na[0]:    ', a[0])        # first row
print('a[-1]:   ', a[-1])       # last row
print('a[1,2]:  ', a[1, 2])     # element at row 1, col 2
print('a[0, :]: ', a[0, :])     # first row, all cols
print('a[:, 2]: ', a[:, 2])     # all rows, col 2

# Slicing [start:stop:step]
print('\na[1:3]:  \n', a[1:3])          # rows 1 and 2
print('a[::2]:  \n', a[::2])           # every other row
print('a[:, 1:4]:\n', a[:, 1:4])      # cols 1,2,3
print('a[1:4, 1:4]:\n', a[1:4, 1:4]) # submatrix

# Boolean indexing extremely powerful for filtering
mask = a > 12
print('\nValues > 12:', a[mask])
print('Rows where first col > 2:', a[a[:, 0] > 2])

# Fancy indexing select specific rows/cols
print('\nRows [0,2,4]:\n', a[[0, 2, 4]])
print('Elements at (0,0),(1,1),(2,2):', a[[0,1,2],[0,1,2]])  # diagonal

# np.where conditional selection
b = np.where(a > 12, a, 0)  # keep values > 12, else 0
print('\nnp.where (>12 keep, else 0):\n', b)

indices = np.where(a % 2 == 0)  # indices of even elements
print('Even element indices:', list(zip(*indices)))

# Views vs copies critical for memory efficiency!
view = a[1:3]   # view shares memory
copy = a[1:3].copy()  # explicit copy

view[0, 0] = 999
print('\nModifying view changes original:', a[1, 0])  # 999
copy[0, 0] = 888
print('Modifying copy does NOT change original:', a[1, 0])  # still 999

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

a[0]:     [1 2 3 4 5]
a[-1]:    [21 22 23 24 25]
a[1,2]:   8
a[0, :]:  [1 2 3 4 5]
a[:, 2]:  [ 3  8 13 18 23]

a[1:3]:  
 [[ 6  7  8  9 10]
 [11 12 13 14 15]]
a[::2]:  
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
a[:, 1:4]:
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]
a[1:4, 1:4]:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Values > 12: [13 14 15 16 17 18 19 20 21 22 23 24 25]
Rows where first col > 2: [[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Rows [0,2,4]:
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
Elements at (0,0),(1,1),(2,2): [ 1  7 13]

np.where (>12 keep, else 0):
 [[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Even element indices: [(np.int64(0), np.int64(1)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(1), np.int64(4)),

---
## 5. Broadcasting <a id='5'></a>

Broadcasting allows operations between arrays of **different shapes** by automatically expanding the smaller array.

### Broadcasting Rules:
1. If arrays have different number of dims, **prepend 1s** to the shape of the smaller array
2. Arrays with size 1 along a dimension are **stretched** to match the other
3. If sizes differ and neither is 1, raise an error

**Example:**
```
Shape A: (3, 4)
Shape B:    (4,)  → expanded to (1, 4) → stretched to (3, 4)
Result:   (3, 4)  ✓

Shape A: (3, 1)
Shape B: (1, 4)
Result:  (3, 4)  ✓ (both broadcast)

Shape A: (3, 4)
Shape B: (3,)   → expanded to (1, 3) can't broadcast to (3, 4) ✗
```

In [6]:
# Scalar broadcasting
a = np.array([1, 2, 3, 4])
print(a + 10)       # [11, 12, 13, 14]
print(a * 2)        # [2, 4, 6, 8]

# 1D + 1D
a = np.array([[1],[2],[3]])    # shape (3, 1)
b = np.array([10, 20, 30])    # shape (3,) → (1, 3)
print('\nBroadcast (3,1) + (1,3):')
print(a + b)  # result: (3, 3)

# Real ML example: normalize features
X = np.random.randn(100, 5)   # (100 samples, 5 features)
mean = X.mean(axis=0)         # (5,) mean of each feature
std  = X.std(axis=0)          # (5,)
X_norm = (X - mean) / std     # broadcast: (100,5) - (5,) / (5,)
print(f'\nNormalized X: mean≈{X_norm.mean():.6f}, std≈{X_norm.std():.6f}')

# Outer product via broadcasting
x = np.array([1, 2, 3])[:, np.newaxis]  # (3, 1)
y = np.array([1, 2, 3])[np.newaxis, :]  # (1, 3)
print('\nOuter product via broadcasting:')
print(x * y)  # (3, 3)
print('Same as np.outer:', np.outer([1,2,3],[1,2,3]))

# Batch matrix operations
batch_vectors  = np.random.randn(32, 64)   # 32 vectors of dim 64
global_bias    = np.random.randn(64)        # single bias vector
result         = batch_vectors + global_bias  # (32, 64) broadcast
print(f'\nBatch + bias: {result.shape}')

[11 12 13 14]
[2 4 6 8]

Broadcast (3,1) + (1,3):
[[11 21 31]
 [12 22 32]
 [13 23 33]]

Normalized X: mean≈-0.000000, std≈1.000000

Outer product via broadcasting:
[[1 2 3]
 [2 4 6]
 [3 6 9]]
Same as np.outer: [[1 2 3]
 [2 4 6]
 [3 6 9]]

Batch + bias: (32, 64)


---
## 6. Mathematical Operations & ufuncs <a id='6'></a>

**Universal functions (ufuncs)** operate element-wise and are implemented in C much faster than Python loops.

Key ufunc families:
- Arithmetic: `add`, `subtract`, `multiply`, `divide`, `power`, `mod`
- Trigonometric: `sin`, `cos`, `tan`, `arcsin`, `arccos`, `arctan`, `arctan2`
- Exponential: `exp`, `exp2`, `log`, `log2`, `log10`, `log1p`, `expm1`
- Comparison: `greater`, `less`, `equal`, `maximum`, `minimum`
- Bitwise: `bitwise_and`, `bitwise_or`, `bitwise_xor`

In [7]:
x = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

# Trigonometric
print('sin:', np.sin(x).round(3))
print('cos:', np.cos(x).round(3))

# Exponential / log
a = np.array([1, 2, 3, 4, 5], dtype=float)
print('exp:', np.exp(a))
print('log:', np.log(a).round(4))
print('log2:', np.log2(a).round(4))
print('log1p (log(1+x)):', np.log1p(a))  # numerically stable for small x
print('expm1 (e^x - 1):', np.expm1(a))  # numerically stable for small x

# Aggregate ufuncs
b = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print('\nsum:    ', np.sum(b))
print('prod:   ', np.prod(b))
print('cumsum: ', np.cumsum(b))
print('cumprod:', np.cumprod(b[:4]))
print('diff:   ', np.diff(b))    # consecutive differences

# Comparison
a, b = np.array([1,5,3,2]), np.array([4,2,3,1])
print('maximum:', np.maximum(a, b))  # element-wise max
print('minimum:', np.minimum(a, b))  # element-wise min
print('clip(2,4):', np.clip(a, 2, 4))  # clamp values

# Activation functions implemented with NumPy
def sigmoid(x): return 1 / (1 + np.exp(-x))
def relu(x): return np.maximum(0, x)
def softmax(x):
    e = np.exp(x - np.max(x))  # subtract max for numerical stability
    return e / e.sum()
def tanh(x): return np.tanh(x)
def gelu(x): return 0.5 * x * (1 + np.tanh(np.sqrt(2/np.pi) * (x + 0.044715 * x**3)))

logits = np.array([2.0, 1.0, 0.1])
print('\nsigmoid:', sigmoid(logits).round(4))
print('relu:   ', relu(np.array([-1, 0, 1, 2])))
print('softmax:', softmax(logits).round(4), '→ sum:', softmax(logits).sum().round(6))

sin: [0.    0.5   0.707 0.866 1.   ]
cos: [1.    0.866 0.707 0.5   0.   ]
exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
log: [0.     0.6931 1.0986 1.3863 1.6094]
log2: [0.     1.     1.585  2.     2.3219]
log1p (log(1+x)): [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
expm1 (e^x - 1): [  1.71828183   6.3890561   19.08553692  53.59815003 147.4131591 ]

sum:     31
prod:    6480
cumsum:  [ 3  4  8  9 14 23 25 31]
cumprod: [ 3  3 12 12]
diff:    [-2  3 -3  4  4 -7  4]
maximum: [4 5 3 2]
minimum: [1 2 3 1]
clip(2,4): [2 4 3 2]

sigmoid: [0.8808 0.7311 0.525 ]
relu:    [0 0 1 2]
softmax: [0.659  0.2424 0.0986] → sum: 1.0


---
## 7. Linear Algebra <a id='7'></a>

Linear algebra is the mathematical language of machine learning.

### Key operations:

**Matrix multiplication:**
$$C_{ij} = \sum_k A_{ik} B_{kj}$$

**Determinant:**
$$\det(A) = \sum_{\sigma} \text{sgn}(\sigma) \prod_i A_{i,\sigma(i)}$$

**Eigendecomposition:** $A = V \Lambda V^{-1}$ where $\Lambda$ is diagonal matrix of eigenvalues

**SVD (Singular Value Decomposition):** $A = U \Sigma V^T$ fundamental for PCA, recommendation systems, image compression

**Norm:**
$$\|x\|_p = \left(\sum_i |x_i|^p\right)^{1/p}$$

In [8]:
A = np.array([[4, 7], [2, 6]], dtype=float)
B = np.array([[3, 1], [5, 2]], dtype=float)

# Matrix multiplication
print('A @ B:\n', A @ B)             # preferred (Python 3.5+)
print('matmul(A,B):\n', np.matmul(A, B))
print('dot(A,B):\n', np.dot(A, B))   # same for 2D

# Inner / outer products
v1, v2 = np.array([1,2,3]), np.array([4,5,6])
print('\nInner (dot):', np.inner(v1, v2))     # scalar
print('Outer:\n', np.outer(v1, v2))           # 3x3 matrix

# Inverse, determinant
print('\nInverse:\n', np.linalg.inv(A))
print('Determinant:', np.linalg.det(A))
print('A @ A^-1 ≈ I:\n', (A @ np.linalg.inv(A)).round(10))

# Solve linear system Ax = b
b = np.array([1, 2])
x = np.linalg.solve(A, b)  # more stable than inv(A) @ b
print('\nSolution x:', x)
print('Verify Ax=b:', A @ x)

# Eigenvalues & eigenvectors
vals, vecs = np.linalg.eig(A)
print('\nEigenvalues:', vals)
print('Eigenvectors:\n', vecs)

# SVD fundamental for PCA
X = np.random.randn(5, 4)
U, S, Vt = np.linalg.svd(X, full_matrices=False)
print(f'\nSVD: U={U.shape}, S={S.shape}, Vt={Vt.shape}')
# Reconstruct: X = U @ diag(S) @ Vt
X_reconstructed = U @ np.diag(S) @ Vt
print('Reconstruction error:', np.max(np.abs(X - X_reconstructed)))

# Rank-k approximation (data compression)
k = 2
X_compressed = U[:, :k] @ np.diag(S[:k]) @ Vt[:k, :]
print(f'Rank-{k} reconstruction error:', np.max(np.abs(X - X_compressed)).round(4))

# Norms
v = np.array([3, 4])
print('\nL1 norm:', np.linalg.norm(v, 1))     # 7.0
print('L2 norm:', np.linalg.norm(v, 2))     # 5.0 (Euclidean)
print('Linf norm:', np.linalg.norm(v, np.inf))  # 4.0
print('Frobenius norm:', np.linalg.norm(A, 'fro'))

A @ B:
 [[47. 18.]
 [36. 14.]]
matmul(A,B):
 [[47. 18.]
 [36. 14.]]
dot(A,B):
 [[47. 18.]
 [36. 14.]]

Inner (dot): 32
Outer:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Determinant: 10.000000000000002
A @ A^-1 ≈ I:
 [[ 1. -0.]
 [ 0.  1.]]

Solution x: [-0.8  0.6]
Verify Ax=b: [1. 2.]

Eigenvalues: [1.12701665 8.87298335]
Eigenvectors:
 [[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]

SVD: U=(5, 4), S=(4,), Vt=(4, 4)
Reconstruction error: 1.3322676295501878e-15
Rank-2 reconstruction error: 0.8354

L1 norm: 7.0
L2 norm: 5.0
Linf norm: 4.0
Frobenius norm: 10.246950765959598


---
## 8. Statistics <a id='8'></a>

In [9]:
data = np.random.normal(loc=5.0, scale=2.0, size=(1000, 10))

# Basic statistics
print('Mean (global):  ', data.mean())
print('Mean (per col): ', data.mean(axis=0).round(3))
print('Mean (per row): ', data.mean(axis=1)[:5].round(3))

print('\nStd:    ', data.std(axis=0).round(3))
print('Var:    ', data.var(axis=0).round(3))
print('Median: ', np.median(data, axis=0).round(3))

# Percentiles / quantiles
print('\n25th percentile:', np.percentile(data, 25, axis=0).round(3))
print('75th percentile:', np.percentile(data, 75, axis=0).round(3))
print('IQR:', (np.percentile(data, 75) - np.percentile(data, 25)).round(3))

# Correlation
X = data[:, :3]
corr = np.corrcoef(X.T)  # note: corrcoef takes (n_features, n_samples)
print('\nCorrelation matrix:')
print(corr.round(3))

# Histogram
counts, bin_edges = np.histogram(data[:, 0], bins=20)
print('\nHistogram bins:', bin_edges[:5].round(2))
print('Counts:', counts[:5])

# Weighted operations
values  = np.array([1, 2, 3, 4, 5])
weights = np.array([0.1, 0.1, 0.2, 0.3, 0.3])
print('\nWeighted mean:', np.average(values, weights=weights))

# Covariance
cov = np.cov(X.T)
print('Covariance matrix shape:', cov.shape)

Mean (global):   5.008479800316198
Mean (per col):  [5.026 5.052 5.11  4.993 5.025 4.991 4.882 5.051 4.968 4.987]
Mean (per row):  [5.21  4.677 4.387 4.448 5.443]

Std:     [2.057 2.053 1.972 1.961 2.025 2.007 1.995 1.876 2.056 2.095]
Var:     [4.232 4.217 3.889 3.845 4.102 4.029 3.981 3.521 4.229 4.391]
Median:  [4.991 5.09  5.09  5.072 5.112 4.975 4.913 5.001 4.931 5.05 ]

25th percentile: [3.636 3.732 3.808 3.712 3.598 3.645 3.492 3.817 3.534 3.617]
75th percentile: [6.433 6.411 6.454 6.277 6.3   6.308 6.145 6.28  6.393 6.383]
IQR: 2.688

Correlation matrix:
[[ 1.     0.043  0.048]
 [ 0.043  1.    -0.089]
 [ 0.048 -0.089  1.   ]]

Histogram bins: [-1.01 -0.39  0.22  0.84  1.46]
Counts: [ 5  6 10 19 33]

Weighted mean: 3.6
Covariance matrix shape: (3, 3)


---
## 9. Array Manipulation <a id='9'></a>

In [10]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])

# Stacking
print('vstack:\n', np.vstack([a, b]))       # vertical adds rows
print('hstack:\n', np.hstack([a, b]))       # horizontal adds cols
print('concatenate axis=0:\n', np.concatenate([a, b], axis=0))

# stack creates a NEW dimension
print('stack axis=0:\n', np.stack([a[0], b[0]], axis=0))  # (2,3)
print('stack axis=1:\n', np.stack([a[0], b[0]], axis=1))  # (3,2)

# Splitting
c = np.arange(12).reshape(4, 3)
parts = np.split(c, 2, axis=0)   # split rows
print('\nSplit rows:', [p.shape for p in parts])

# Sort
x = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print('\nsort:    ', np.sort(x))
print('argsort: ', np.argsort(x))    # indices that would sort x
print('argmax:  ', np.argmax(x))     # index of max
print('argmin:  ', np.argmin(x))     # index of min

# tile and repeat
t = np.array([1, 2, 3])
print('tile(2):  ', np.tile(t, 2))       # [1,2,3,1,2,3]
print('tile(2,2):\n', np.tile(t, (2,2))) # 2D tiling
print('repeat(2):', np.repeat(t, 2))     # [1,1,2,2,3,3]

# Set operations
a, b = np.array([1,2,3,4,5]), np.array([3,4,5,6,7])
print('\nunique:      ', np.unique([1,2,2,3,3,3]))
print('union1d:     ', np.union1d(a, b))
print('intersect1d: ', np.intersect1d(a, b))
print('setdiff1d:   ', np.setdiff1d(a, b))  # in a but not b
print('isin:        ', np.isin([2,4,6], a))  # membership test

vstack:
 [[1 2 3]
 [4 5 6]]
hstack:
 [[1 2 3 4 5 6]]
concatenate axis=0:
 [[1 2 3]
 [4 5 6]]
stack axis=0:
 [[1 2 3]
 [4 5 6]]
stack axis=1:
 [[1 4]
 [2 5]
 [3 6]]

Split rows: [(2, 3), (2, 3)]

sort:     [1 1 2 3 4 5 6 9]
argsort:  [1 3 6 0 2 4 7 5]
argmax:   5
argmin:   1
tile(2):   [1 2 3 1 2 3]
tile(2,2):
 [[1 2 3 1 2 3]
 [1 2 3 1 2 3]]
repeat(2): [1 1 2 2 3 3]

unique:       [1 2 3]
union1d:      [1 2 3 4 5 6 7]
intersect1d:  [3 4 5]
setdiff1d:    [1 2]
isin:         [ True  True False]


---
## 10. Random Module <a id='10'></a>

In [11]:
# ===== Modern API (NumPy 1.17+) use this =====
rng = np.random.default_rng(seed=42)

# Uniform distribution [0, 1)
print('Uniform:', rng.random(5))

# Normal (Gaussian) distribution: N(μ, σ²)
print('Normal(0,1):', rng.standard_normal(5).round(3))
print('Normal(5,2):', rng.normal(loc=5, scale=2, size=5).round(3))

# Integer
print('Integers:', rng.integers(0, 10, size=5))

# Choice
arr = np.arange(10)
print('Choice (no replace):', rng.choice(arr, size=5, replace=False))
print('Choice (replace):   ', rng.choice(arr, size=5, replace=True))

# Shuffle (in-place)
arr_copy = arr.copy()
rng.shuffle(arr_copy)
print('Shuffled:', arr_copy)

# Various distributions
print('Binomial:  ', rng.binomial(n=10, p=0.5, size=5))
print('Poisson:   ', rng.poisson(lam=3, size=5))
print('Uniform[a,b]:', rng.uniform(-1, 1, size=5).round(3))
print('Exponential:', rng.exponential(scale=2, size=5).round(3))

# Weight initialization patterns from deep learning
n_in, n_out = 256, 128

# Xavier/Glorot initialization
limit = np.sqrt(6 / (n_in + n_out))
W_xavier = rng.uniform(-limit, limit, (n_in, n_out))

# He (Kaiming) initialization for ReLU
W_he = rng.normal(0, np.sqrt(2 / n_in), (n_in, n_out))

print(f'\nXavier init std: {W_xavier.std():.4f}')
print(f'He init std:     {W_he.std():.4f}')

Uniform: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Normal(0,1): [-1.302  0.128 -0.316 -0.017 -0.853]
Normal(5,2): [6.759 6.556 5.132 7.254 5.935]
Integers: [4 2 0 5 8]
Choice (no replace): [6 9 7 2 0]
Choice (replace):    [0 9 4 8 6]
Shuffled: [6 3 8 2 9 5 1 7 4 0]
Binomial:   [8 4 4 5 4]
Poisson:    [2 5 4 1 6]
Uniform[a,b]: [-0.771  0.337 -0.058  0.13   0.53 ]
Exponential: [4.213 3.29  2.087 1.185 0.089]

Xavier init std: 0.0721
He init std:     0.0885


---
## 11. Performance & Vectorization <a id='11'></a>

In [12]:
import time

n = 1_000_000
a = np.random.randn(n)
b = np.random.randn(n)

# Python loop vs NumPy vectorization
def loop_dot(a, b):
    total = 0.0
    for x, y in zip(a, b):
        total += x * y
    return total

# Time loop
start = time.time()
loop_dot(a[:10000], b[:10000])  # only 10k for demo
loop_time = time.time() - start

# Time numpy
start = time.time()
np.dot(a[:10000], b[:10000])
numpy_time = time.time() - start

print(f'Loop:  {loop_time*1000:.3f} ms')
print(f'NumPy: {numpy_time*1000:.3f} ms')
print(f'Speedup: {loop_time/max(numpy_time, 1e-9):.0f}x')

# Memory efficiency views avoid copying
large = np.random.randn(1000, 1000)
import sys

view = large[:500, :500]    # 0 extra memory
copy = large[:500, :500].copy()  # full copy

print(f'\nView nbytes: {view.nbytes} (shares with original)')
print(f'Copy nbytes: {copy.nbytes} (independent)')

# Avoid implicit copies with in-place operations
a = np.ones(n)
a += 1    # in-place, no copy
a *= 2    # in-place

# Prefer np.add(out=...) for repeated operations
result = np.empty(n)
np.add(a, b, out=result)  # writes directly to result, no temp array
print('\nIn-place add completed')

Loop:  1.789 ms
NumPy: 0.080 ms
Speedup: 22x



View nbytes: 2000000 (shares with original)
Copy nbytes: 2000000 (independent)

In-place add completed


---
## 12. Advanced: einsum <a id='12'></a>

`np.einsum` (Einstein summation notation) expresses any linear algebra operation concisely and often more efficiently.

Notation: `'ij,jk->ik'` means:
- `i,j` are indices of first operand
- `j,k` are indices of second operand
- `i,k` are indices of output
- shared index `j` is summed over (contracted)

In [13]:
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
v = np.random.randn(4)

# Matrix multiplication: C_ik = sum_j A_ij * B_jk
print('matmul:', np.allclose(np.einsum('ij,jk->ik', A, B), A @ B))

# Dot product: scalar = sum_i v_i * w_i
print('dot:   ', np.allclose(np.einsum('i,i->', v, v), np.dot(v, v)))

# Outer product: M_ij = v_i * w_j
print('outer: ', np.allclose(np.einsum('i,j->ij', v, v), np.outer(v, v)))

# Trace: sum of diagonal elements
M = np.random.randn(4, 4)
print('trace: ', np.allclose(np.einsum('ii->', M), np.trace(M)))

# Batch matrix multiply (crucial in transformers!)
# Q, K, V in attention: (batch, heads, seq_len, head_dim)
Q = np.random.randn(32, 8, 64, 64)   # (batch, heads, seq, d_head)
K = np.random.randn(32, 8, 64, 64)
# Attention scores: (batch, heads, seq_q, seq_k)
scores = np.einsum('bhqd,bhkd->bhqk', Q, K)
print(f'\nAttention scores shape: {scores.shape}')  # (32, 8, 64, 64)

# Element-wise multiply then sum along axis
print('hadamard then sum:', np.einsum('ij,ij->i', A, A).shape)  # (3,)

matmul: True
dot:    True
outer:  True
trace:  True



Attention scores shape: (32, 8, 64, 64)
hadamard then sum: (3,)


---
## 13. Additional Learning Resources <a id='13'></a>

### Official Documentation
- **NumPy Official Docs**: https://numpy.org/doc/stable/
- **NumPy User Guide**: https://numpy.org/doc/stable/user/index.html
- **NumPy API Reference**: https://numpy.org/doc/stable/reference/index.html

### Papers
- **Array programming with NumPy** (Harris et al., Nature 2020): https://www.nature.com/articles/s41586-020-2649-2

### Free Books & Tutorials
- **From Python to NumPy** (Nicolas Rougier, FREE): https://www.labri.fr/perso/nrougier/from-python-to-numpy/
- **Python Data Science Handbook** (VanderPlas, FREE): https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- **Scientific Python Lectures**: https://lectures.scientific-python.org/intro/numpy/index.html

### Practice
- **100 NumPy Exercises**: https://github.com/rougier/numpy-100
- **NumPy Exercises (w3resource)**: https://www.w3resource.com/python-exercises/numpy/index.php

### Cheat Sheets
- **NumPy Cheat Sheet (DataCamp)**: https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-python
- **NumPy Illustrated**: https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d